apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      hostPort:
        enabled: true
      kind: DaemonSet
      service:
        enabled: false
      extraArgs:
        default-ssl-certificate: "nginx-ingress/hikoru-prod-tls-secret"
      config:
        annotation-value-word-blocklist: "load_module,lua_package,_by_lua,location,root,proxy_pass,serviceaccount,{,},',\""
        # ipv6 is disabled cluster wide for now
        disable-ipv6: "true"
        use-http2: "true"
        use-geoip: "false"
        ssl-protocols: TLSv1.3
        ssl-redirect: "true"
        force-ssl-redirect: "true"
        whitelist-source-range: "192.168.0.0/24,10.69.0.0/16"
        # too many requests
        limit-req-status-code: "429"
        # i'm a teapot ;)
        limit-conn-status-code: "418"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: nginx-ingress
          namespaceSelector:
            any: true
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
