# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname harbor
  namespace: flux-system
spec:
  targetNamespace: harbor
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/harbor/app/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
