---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name postgres
spec:
  postgresVersion: 16

  # patroni: # turn on sync writes to at least 1 other replica
  #   dynamicConfiguration:
  #     synchronous_mode: true
  #     postgresql:
  #       max_wal_size: 5GB
  #       synchronous_commit: "on"
  #       pg_hba:
  #         - hostnossl all all 10.244.0.0/16 md5 # Needed because dbman does not support SSL yet
  #         - hostssl all all all md5

  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      replicas: &replica 1
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/data: postgres

  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
         - --type=full
      configuration:
        - secret:
            name: crunchy-postgres-secret
      global:
        repo1-s3-uri-style: path
        repo1-path: /pgbackrest/postgres-operator/hikoru/repo1
        repo1-retention-full: "14"
        repo1-retention-full-type: count
      repos:
        - name: repo1
          s3:
            bucket: crunchy-postgres-backups
            endpoint: https://truenas.samoth.eu:9000
            region: us-east-1
          schedules:
            full: "0 1 * * 0" # Sunday at 01:00
            differential: "0 1 * * 1-6" # Mon-Sat at 01:00

  proxy:
    pgBouncer:
      port: 5432
      replicas: *replica
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-pgbouncer
      config:
        global:
          pool_mode: "transaction" # pgBouncer is set to transaction for Authentik. Grafana requires session https://github.com/grafana/grafana/issues/74260#issuecomment-1702795311. Everything else is happy with transaction
          client_tls_sslmode: require
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/role: "pgbouncer"

  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M

  users:
    # Superuser
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: harbor
      databases:
        - harbor
      password:
        type: AlphaNumeric
    - name: movtrack6
      databases:
        - movtrack6
      password:
        type: AlphaNumeric
    - name: rsscachego
      databases:
        - rsscachego
      password:
        type: AlphaNumeric
