apiVersion: v1
kind: Secret
metadata:
    name: postgres-pguser-harbor
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:IQEO5DWnGQi6Veb+4JPnATjccXsTZaLJ,iv:G8d8h85uWEe9pgVCB1DskWsgacM0MwWBMf+wXsrVKMk=,tag:sNhtWPusW11iWwVW6Lw9ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2u6camdac38mn94r8dfmqqpmjfcphzjh4vcyx4gath40rsjpdvsl8wt3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMamswUDd1UXB0dWRScG94
            aDRWS3hwQ3ZCN09pb0hReTdIVU5kWHdWVERFClVkTU9RSGhRNWdDQlBQMmg2TktF
            MGZmZ21vbHNTSCsxbDRRMGc2NklqVmcKLS0tIG9OTHZ1RlpoK1lhajdqVVcrRDM3
            cVplcmZQVXNERTg2NUdXNjBrSzB1NkEK7ROGbd/QfbM62Kdda+ByvDRu/bTtxYl7
            2Lzw0ZJ6BCAw7NKLlyiSfm6NUm527FdS0MHGDr8YLpJjjOGABXLV+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-29T19:58:15Z"
    mac: ENC[AES256_GCM,data:POtUkx4xq/bh9J9EjNVgLO8ysltrgsQGlMtamVE+m02R2PQMTl+MfiUcD9cWL4gNn8j9WTLAGR0i/v73kCLW/Kj668fnOovHDpQkwM5nuAwb42pzhwXDtQxNkSRc73Pb7tKncorhao3GthW3GufnBsmr3TROSpMVbqdqQHI/Wx0=,iv:nWEuqBfVGI9ELaCZ1LekuTOSRYf1fNEUI1OiWR6CxGQ=,tag:3wFlJv0p8olTiGXsQQRHVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
